name: "Textile Bucket - Deploy"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  bucket_push:
    runs-on: ubuntu-latest
    name: push textile bucket
    steps:
    - name: push action
      id: bucket
      uses: textileio/github-action-buckets@master
      with:
        key: ${{ secrets.TEXTILE_ACCOUNT_KEY }}
        secret: ${{ secrets.TEXTILE_ACCOUNT_SECRET }}
        bucket: 'tableland-todo'
        thread: 'bafkyusjf6fdhzkub3fstqvdvis2nrpwxcefzeo3wtfw5wag37y3jz5q'
        path: 'tableland-todo/dist'
